# Generated by Django 4.1.2 on 2022-10-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='user',
        ),
        migrations.AddField(
            model_name='smslog',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smslog',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
