# Generated by Django 4.0.3 on 2022-10-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='car',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
