# Generated by Django 4.1.2 on 2022-10-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderhistory_to_city_orderhistory_to_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='to_region',
        ),
    ]
